# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
variables:
- name: buildConfiguration
  value: Release
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      displayName: dotnet build $(buildConfiguration)
      inputs:
        script: dotnet build --configuration $(buildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: dotnet publish --configuration $(buildConfiguration) -- output $(Build.ArtifactStagingDirectory)
      inputs:
        command: publish
        publishWebProjects: false
        projects: JavaCourseAPI/JavaCourseAPI.csproj
        arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      displayName: publish artifacts
      
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure dla studentów (95b577dc-ed59-4d96-b74a-0b54bdd47ef9)'
        appType: 'webAppLinux'
        WebAppName: 
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

